---
- name: Prepare for update all nodes
  hosts: openstack_nodes, undercloud
  roles:
          - prep
- name: Minor update Undercloud
  gather_facts: false
  hosts: undercloud
  roles:
          - undercloud-update
- name: Prepare test envs
  gather_facts: false
  hosts: undercloud
  roles:
          - test-prep
- name: Run test
  gather_facts: false
  hosts: undercloud
  roles:
          - test-run
- name: Minor update Overcloud
  gather_facts: false
  hosts: undercloud
  roles:
          - overcloud-update
- name: Reboot overcloud and finish all nodes
  hosts: overcloud_nodes:!unused:!compute
  gather_facts: false
  serial: 1
  roles:
          - overcloud-reboot
- name: Reboot overcloud computes and finish all nodes
  hosts: compute:!unused
  gather_facts: false
  serial: "{{ ((groups['compute'] | length)  * 0.2) | round(0,'ceil') | int }}"
  roles:
          - overcloud-reboot
- name: Finish update on all nodes
  hosts: openstack_nodes, undercloud
  strategy: free
  roles:
          - post
