---
- name: Prepare for update all nodes
  hosts: openstack_nodes, undercloud
  roles:
          - prep
- name: Minor update Undercloud
  gather_facts: false
  hosts: undercloud
  roles:
          - undercloud-update
- name: Minor update Overcloud
  gather_facts: false
  hosts: undercloud
  roles:
          - overcloud-update
- name: Reboot overcloud computes and finish all nodes
  hosts: compute:!unused
  gather_facts: false
  serial: 1
  roles:
          - overcloud-reboot

- name: Magical arithmetics with compute nodes
  vars:
    parallel_compute_reboots: "{{ ((groups['computes'] | length)  * 0.2) | round(0,'ceil') | int }}"
- name: Reboot overcloud and finish all nodes
  hosts: overcloud_nodes:!unused:!compute
  gather_facts: false
  serial: parallel_compute_reboots
  roles:
          - overcloud-reboot
- name: Finish update on all nodes
  hosts: openstack_nodes, undercloud
  strategy: free
  roles:
          - post
