- name: Enable OSP11 repo
  shell: |
          sudo rhos-release -x
          sudo rhos-release 11 rhel-7.6
- name: Check OSP11 update
  shell: sudo yum check-update
  ignore_errors: true
  register: update
- name: Run undercloud upgrade to OSP11
  shell: |
          sudo yum-config-manager --setopt=exclude=rhosp-director-images* --save && \
          sudo systemctl stop openstack-* neutron-* httpd && \
          sudo yum update -y instack-undercloud openstack-puppet-modules openstack-tripleo-common python-tripleoclient && \
          source ~/stackrc && \
          openstack undercloud upgrade
  when: update is failed
- name: Check OSP11 update
  shell: sudo yum check-update
  ignore_errors: true
- name: Reboot UC OSP11
  include: reboot.yml
  when: update is failed
- name: Enable OSP12 repo
  shell: |
          sudo rhos-release -x
          sudo rhos-release 12 rhel-7.6
- name: Check OSP12 update
  shell: sudo yum check-update
  ignore_errors: true
  register: update
- name: Run undercloud upgrade to OSP12
  shell: |
          sudo yum-config-manager --setopt=exclude=rhosp-director-images* --save && \
          sudo systemctl stop openstack-* neutron-* httpd && \
          sudo yum update -y instack-undercloud openstack-puppet-modules openstack-tripleo-common python-tripleoclient && \
          source ~/stackrc && \
          openstack undercloud upgrade
  when: update is failed
- name: Check OSP12 update
  shell: sudo yum check-update
  ignore_errors: true
- name: Reboot UC OSP12
  include: reboot.yml
  when: update is failed
- name: Enable OSP13 repo
  shell: |
          sudo rhos-release -x
          sudo rhos-release 13 rhel-7.6
- name: Check OSP13 update
  shell: sudo yum check-update
  ignore_errors: true
  register: update
- name: Run undercloud upgrade to OSP13
  shell: |
          sudo yum-config-manager --setopt=exclude= --save && \
          sudo yum update -y python-tripleoclient instack-undercloud && \
          source ~/stackrc && \
          openstack undercloud upgrade
  when: update is failed
- name: Check OSP13 update
  shell: sudo yum check-update
- name: Reboot UC OSP13
  include: reboot.yml
  when: update is failed
