---
- name: Copy patches
  copy:
         src: "{{ role_path }}/files/0001-Make-minor-update-more-graceful.patch"
         dest: /home/stack/0001-Make-minor-update-more-graceful.patch
- name: Patch templates
  ignore_errors: true
  shell: |
          sudo patch -Nfs -d /usr/share/openstack-tripleo-heat-templates/ -p1 < /home/stack/0001-Make-minor-update-more-graceful.patch
- name: Create overcloud_update.sh
  shell: |
          cp overcloud_deploy.sh overcloud_update.sh && \
          sed -i -e 's/deploy \\/deploy --update-plan-only \\/' overcloud_update.sh
          sed -i -e 's/timeout 100/timeout 333/' overcloud_update.sh
- name: Create overcloud plan
  shell: |
          source ~/stackrc
          sh overcloud_update.sh 2>&1 | tee overcloud_update.log
- name: Get stack from overcloud_update.sh
  shell: |
          source ~/stackrc
          openstack stack list  -f value -c "Stack Name"
  register: stack_name
- name: Run overcloud update
  shell: |
          source ~/stackrc
          INPUT=$(openstack server list -f value -c Name | grep -v controller | tr '\n' '|' | sed 's/|$//')
          printf "${INPUT}\n\n\n\n\n" | openstack overcloud update stack -i "{{stack_name.stdout}}" 2>&1 | tee -a overcloud_update.log
- name: Check successfull update
  shell: |
          source ~/stackrc
          openstack stack list -c 'Stack Status' -f value | grep COMPLETE
