---
- name: Create overcloud_update.sh
  shell: |
          cp overcloud_deploy.sh overcloud_update.sh && \
          sed -i -e 's/deploy \\/deploy --update-plan-only \\/' overcloud_update.sh
- name: Create overcloud plan
  shell: |
          source ~/stackrc
          sh overcloud_update.sh 2>&1 | tee overcloud_update.log
- name: Run overcloud update
  shell: |
          source ~/stackrc
          yes '' | openstack overcloud update stack -i overcloud 2>&1 | tee -a overcloud_update.log
