---
- name: Undercloud upgrade
  gather_facts: false
  hosts: undercloud
  roles:
          - undercloud-update
- name: Run shaker
  gather_facts: false
  hosts: undercloud
  roles:
          - test-run
- name: Prepair undercloud
  gather_facts: false
  hosts: undercloud
  roles:
          - ffwd-prepare
