---
- name:  Shaker
  async: 10000
  poll: 0
  shell: |
          . ~/.shaker/bin/activate
          source ~/overcloudrc.v3
          sudo  iptables -I INPUT 1 -p tcp --dport 9999 -j ACCEPT
          sudo  iptables -I INPUT 1 -p udp --dport 9999 -j ACCEPT
          export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt
          shaker --scenario openstack/full_l2 --matrix "{time: 1600}" --agent-join-timeout 900 \
                 --external-net public --os-insecure --flavor-name shaker-flavor --image-name shaker-image \
                 --server-endpoint $(ip -f inet -o addr show eth2 | cut -d\  -f 7 | cut -d/ -f 1):9999 \
                 --book ~/shaker_report_$(date +%s)/ --os-region regionOne 2>&1 | tee shaker_run.log
- name: pause 5min
  pause:
          minutes: 5
- name:  Tempest
  async: 10000
  poll: 0
  shell: |
          . ~/.tempest/bin/activate
          source ~/overcloudrc.v3
          export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt
          cd tempest
          tox -e full 2>&1 | tee ~/tempest_run.log
- name: pause 1min
  pause:
          minutes: 1
